name = "Havoc Retfart S5"
author = "minecraftbossdj"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bcb9cc330cce42d820f05ed6592f4be3609f8755fe5a8ed97d75db52f5c7554f"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
